# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Projets/Nales/nales/nales/uic/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(971, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centralwidget.sizePolicy().hasHeightForWidth()
        )
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.top_frame_container = QtWidgets.QWidget(self.centralwidget)
        self.top_frame_container.setObjectName("top_frame_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_frame_container)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self._ribbon = RibbonWidget(self.top_frame_container)
        self._ribbon.setObjectName("_ribbon")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self._ribbon)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_2.addWidget(self._ribbon)
        self.verticalLayout_3.addWidget(self.top_frame_container)
        self.center_app_container = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.center_app_container.sizePolicy().hasHeightForWidth()
        )
        self.center_app_container.setSizePolicy(sizePolicy)
        self.center_app_container.setObjectName("center_app_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.center_app_container)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_8 = QtWidgets.QSplitter(self.center_app_container)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.left_panel_container = QtWidgets.QWidget(self.splitter_8)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.left_panel_container.sizePolicy().hasHeightForWidth()
        )
        self.left_panel_container.setSizePolicy(sizePolicy)
        self.left_panel_container.setObjectName("left_panel_container")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.left_panel_container)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.splitter = QtWidgets.QSplitter(self.left_panel_container)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tree_view_container = QtWidgets.QWidget(self.splitter)
        self.tree_view_container.setObjectName("tree_view_container")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tree_view_container)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.modeling_ops_tree = ModelingOpsView(self.tree_view_container)
        self.modeling_ops_tree.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.modeling_ops_tree.sizePolicy().hasHeightForWidth()
        )
        self.modeling_ops_tree.setSizePolicy(sizePolicy)
        self.modeling_ops_tree.setMinimumSize(QtCore.QSize(0, 100))
        self.modeling_ops_tree.setSizeIncrement(QtCore.QSize(1, 0))
        self.modeling_ops_tree.setBaseSize(QtCore.QSize(200, 0))
        self.modeling_ops_tree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.modeling_ops_tree.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.modeling_ops_tree.setObjectName("modeling_ops_tree")
        self.verticalLayout_6.addWidget(self.modeling_ops_tree)
        self.param_table_view_container = QtWidgets.QWidget(self.splitter)
        self.param_table_view_container.setObjectName("param_table_view_container")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.param_table_view_container)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.param_table_view_container)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.param_label = QtWidgets.QLabel(self.widget)
        self.param_label.setObjectName("param_label")
        self.horizontalLayout.addWidget(self.param_label)
        self.add_param_btn = QtWidgets.QPushButton(self.widget)
        self.add_param_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/icons/plus_dm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.add_param_btn.setIcon(icon)
        self.add_param_btn.setObjectName("add_param_btn")
        self.horizontalLayout.addWidget(self.add_param_btn)
        self.rmv_param_btn = QtWidgets.QPushButton(self.widget)
        self.rmv_param_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/icons/minus_dm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.rmv_param_btn.setIcon(icon1)
        self.rmv_param_btn.setObjectName("rmv_param_btn")
        self.horizontalLayout.addWidget(self.rmv_param_btn)
        self.verticalLayout_5.addWidget(self.widget)
        self.param_table_view = QtWidgets.QTableView(self.param_table_view_container)
        self.param_table_view.setObjectName("param_table_view")
        self.verticalLayout_5.addWidget(self.param_table_view)
        self.verticalLayout_7.addWidget(self.splitter)
        self.console_viewer_container = QtWidgets.QWidget(self.splitter_8)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.console_viewer_container.sizePolicy().hasHeightForWidth()
        )
        self.console_viewer_container.setSizePolicy(sizePolicy)
        self.console_viewer_container.setObjectName("console_viewer_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.console_viewer_container)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.console_viewer_container)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
        self.splitter_3.setSizePolicy(sizePolicy)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.viewer = OCCTWidget(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.viewer.sizePolicy().hasHeightForWidth())
        self.viewer.setSizePolicy(sizePolicy)
        self.viewer.setMinimumSize(QtCore.QSize(0, 100))
        self.viewer.setSizeIncrement(QtCore.QSize(1, 0))
        self.viewer.setBaseSize(QtCore.QSize(800, 500))
        self.viewer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.viewer.setObjectName("viewer")
        self.console_container = QtWidgets.QWidget(self.splitter_3)
        self.console_container.setObjectName("console_container")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.console_container)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self._console = ConsoleWidget(self.console_container)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._console.sizePolicy().hasHeightForWidth())
        self._console.setSizePolicy(sizePolicy)
        self._console.setMinimumSize(QtCore.QSize(0, 50))
        self._console.setObjectName("_console")
        self.verticalLayout_4.addWidget(self._console)
        self.verticalLayout.addWidget(self.splitter_3)
        self.verticalLayout_2.addWidget(self.splitter_8)
        self.verticalLayout_3.addWidget(self.center_app_container)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setEnabled(False)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 971, 20))
        self.menuBar.setDefaultUp(False)
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.param_label.setText(_translate("MainWindow", "Parameters"))


from nales.views.tree_views import ModelingOpsView
from nales.widgets.console import ConsoleWidget
from nales.widgets.occt_widget import OCCTWidget
from nales.widgets.ribbon_widget import RibbonWidget
from nales.resources import resources_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
